### ISSUE TITLE
[Bug]: meme not getting generated it's half

### ISSUE THREAD

**Issue by askadityapandey** [avalynndev/memergez#42]
### What went wrong?

You can see the screenshot I provided

### How'd you stumble upon it?

![image](https://github.com/user-attachments/assets/da010796-92fd-41b2-a1db-b3763a97ae26)
It;s simple to produce this issue, just chose a meme (on the screenshot)
If you want I can help to solve this bug.

### What you hoped for vs. What actually happened

A full meme

### Anything else we should know?

I use arch btw, and the browser is Brave.

### Which browsers were a bummer?

Chrome

### Code of Conduct Agreement

- [x] I agree to follow this project's Code of Conduct.

**Comment by avalynndev** [comment]
Actually even tho the image is generated.. the problem is the image isn't shown in full height and width so right click on it and click on show in new tab.. it will show the full picture

**Comment by askadityapandey** [comment]
> Actually even tho the image is generated.. the problem is the image isn't shown in full height and width so right click on it and click on show in new tab.. it will show the full picture

lmao kid, you closed the issue?

**Comment by avalynndev** [comment]
uh the problem.. is solved fyi
